CREATE DATABASE FilmoviDB;
GO

USE FilmoviDB;
GO

CREATE TABLE Korisnik (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    KorisnickoIme NVARCHAR(100) NOT NULL UNIQUE,
    BrojNagrada INT NOT NULL DEFAULT 0
);

CREATE TABLE Zanr (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Naziv NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Film (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Naslov NVARCHAR(100) NOT NULL,
    Reziser NVARCHAR(100) NOT NULL
);

CREATE TABLE Tag (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Naziv NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE FilmZanr (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FilmId INT NOT NULL,
    ZanrId INT NOT NULL,
    CONSTRAINT FK_FilmZanr_Film FOREIGN KEY (FilmId) 
        REFERENCES Film(Id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT FK_FilmZanr_Zanr FOREIGN KEY (ZanrId) 
        REFERENCES Zanr(Id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT UQ_FilmZanr_Film_Zanr UNIQUE (FilmId, ZanrId)
);

CREATE TABLE FilmTag (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FilmId INT NOT NULL,
    TagId INT NOT NULL,
    CONSTRAINT FK_FilmTag_Film FOREIGN KEY (FilmId) 
        REFERENCES Film(Id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT FK_FilmTag_Tag FOREIGN KEY (TagId) 
        REFERENCES Tag(Id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT UQ_FilmTag_Film_Tag UNIQUE (FilmId, TagId)
);

CREATE TABLE Ocena (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    KorisnikId INT NOT NULL,
    FilmId INT NOT NULL,
    Vrednost INT NOT NULL CHECK (Vrednost BETWEEN 1 AND 10),
    CONSTRAINT FK_Ocena_Korisnik FOREIGN KEY (KorisnikId) 
        REFERENCES Korisnik(Id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT FK_Ocena_Film FOREIGN KEY (FilmId) 
        REFERENCES Film(Id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT UQ_Ocena_Korisnik_Film UNIQUE (KorisnikId, FilmId)
);

CREATE TABLE ListaZaGledanje (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    KorisnikId INT NOT NULL,
    FilmId INT NOT NULL,
    CONSTRAINT FK_ListaZaGledanje_Korisnik FOREIGN KEY (KorisnikId) 
        REFERENCES Korisnik(Id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT FK_ListaZaGledanje_Film FOREIGN KEY (FilmId) 
        REFERENCES Film(Id) ON UPDATE CASCADE ON DELETE NO ACTION,
    CONSTRAINT UQ_ListaZaGledanje_Korisnik_Film UNIQUE (KorisnikId, FilmId)
);
GO